minor refactoring

diff --git a/owl b/owl
--- a/owl
+++ b/owl
@@ -8,7 +8,7 @@ OWL_SUDO_WARN=${OWL_SUDO_WARN:-true}
 OWL_IGNORE_OUTDATED=${OWL_IGNORE_OUTDATED:-false}
 
 usage() {
-    printf "usage: $(basename "$0") <action> [...]\n"
+    printf 'usage: %s <action> [...]\n' "${0##*/}"
     exit 1
 }
 
@@ -23,6 +23,10 @@ green() {
 magenta() {
     printf "\033[1;35m%s\033[0m" "$@"
 }
+
+missing_pkg() {
+    echo "package '$@' was not found" >&2
+} 
 
 warning() {
     if [ -t 1 ] ; then
@@ -53,7 +57,7 @@ getinfos() {
         if [ $? -ne 0 ] ; then
             cower -i "$1" > "$tmp_out" 2>&1
             if [ $? -ne 0 ] ; then
-                echo "package '$1' was not found" >&2
+                missing_pkg "$1"
                 exit 1
             fi
         fi
@@ -269,7 +273,7 @@ case $action in
             pkgname=$1
             pacman -Q "$pkgname" > /dev/null 2>&1
             if [ $? -ne 0 ] ; then
-                echo "package '$pkgname' was not found" >&2
+                missing_pkg "$pkgname"
                 exit 1
             fi
             previous_pkg=$(ls -1tc "$XDG_PACMAN_CACHE/$pkgname"-[0-9]* 2> /dev/null | head -n 2 | tail -n 1)
@@ -316,7 +320,7 @@ case $action in
                     done
                     : > "$tmp_out"
                 else
-                    echo "package '$1' was not found" >&2
+                    missing_pkg "$1"
                 fi
             fi
             shift
