outputs refactoring

diff --git a/owl b/owl
--- a/owl
+++ b/owl
@@ -8,32 +8,39 @@ OWL_SUDO_WARN=${OWL_SUDO_WARN:-true}
 OWL_IGNORE_OUTDATED=${OWL_IGNORE_OUTDATED:-false}
 
 usage() {
-    printf 'usage: %s <action> [...]\n' "${0##*/}"
+    printf "usage: %s <action> [...]\n" "${0##*/}"
     exit 1
 }
 
+printc() {
+    color=$1
+    shift
+    if [ -t 1 ] ; then
+        printf "\033[%sm%s\033[0m" "$color" "$@"
+    else
+        printf "%s" "$@"
+    fi
+}
+
 white() {
-    printf "\033[1;37m%s\033[0m" "$@"
+    printc "1;37" "$@"
 }
 
 green() {
-    printf "\033[1;32m%s\033[0m" "$@"
+    printc "1;32" "$@"
 }
 
 magenta() {
-    printf "\033[1;35m%s\033[0m" "$@"
+    printc "1;35" "$@"
 }
 
 missing_pkg() {
-    echo "package '$@' was not found" >&2
+    printf "package '%s' was not found\n" "$@" >&2
 } 
 
 warning() {
-    if [ -t 1 ] ; then
-        printf "$(magenta '==>') $(white "$@")"
-    else
-        printf "==> $@"
-    fi
+    magenta "==>"
+    white " $@"
 }
 
 sudorun() {
@@ -168,12 +175,8 @@ case $action in
             pkgname=${from_home%%/*}
             pacman -Q "$pkgname" > /dev/null 2>&1
             if [ $? -eq 1 ] ; then
-                if [ -t 1 ] ; then
-                    magenta "==> "
-                    white "$pkgname "
-                else
-                    printf "%s" "==> $pkgname "
-                fi
+                magenta "==> "
+                white "$pkgname "
                 printf "%s\n" "is not installed"
                 printf "%s" "remove it from the cache [y/N]? "
                 read answer
@@ -184,14 +187,9 @@ case $action in
                 esac
                 continue
             fi
-            if [ -t 1 ] ; then
-                green "$pkgname"
-                printf "\n"
-            else
-                printf "%s\n" "$pkgname"
-            fi
+            green "$pkgname\n"
             if owl_update_repository "$repo" ; then
-                echo -n "reinstall package '$pkgname' [Y/n]? "
+                printf "reinstall package '%s' [Y/n]? " "$pkgname"
                 read answer
                 [ -z "$answer" ] && answer="yes"
                 case "$answer" in
@@ -266,7 +264,7 @@ case $action in
         ;;
     downgrade)
         if [ ! -d "$XDG_PACMAN_CACHE" ] ; then
-            echo "pacman's cache directory doesn't exist" >&2
+            printf "%s\n" "pacman's cache directory doesn't exist" >&2
             exit 1
         fi
         while [ $# -gt 0 ] ; do
@@ -333,7 +331,7 @@ case $action in
             if [ -e "$i" ] ; then
                 ext=${i##*.}
                 if [ "$ext" != "pacsave" ] ; then
-                    echo -n "merge '$i' [y/N]? "
+                    printf "merge '%s' [y/N]? " "$i"
                     read answer
                     case "$answer" in
                         y|yes|Y|Yes)
@@ -341,7 +339,7 @@ case $action in
                             ;;
                     esac
                 fi
-                echo -n "remove '$i' [y/N]? "
+                printf "remove '%s' [y/N]? " "$i"
                 read answer
                 case "$answer" in
                     y|yes|Y|Yes)
@@ -357,7 +355,7 @@ case $action in
             if [ -n "$uri" ] ; then
                 $BROWSER $uri > /dev/null 2>&1
             else
-                echo "package '$1' is not in AUR" >&2
+                printf "package '%s' is not in AUR\n" "$1" >&2
             fi
             shift
         done
@@ -373,13 +371,13 @@ case $action in
         while [ $# -gt 0 ] ; do
             uri=$(getinfos "$1" | grep -m 1 -o 'https\?://.*')
             if [ -n "$uri" ] ; then
-                echo "$1: $uri"
+                printf "%s: %s\n" "$1" "$uri"
                 $BROWSER $uri > /dev/null 2>&1
                 counter=$((counter+1))
             fi
             shift
             if [ $((counter % OWL_MAX_URL)) -eq 0 -a $counter -gt 0 -a $# -gt 0 ] ; then
-                echo -n "continue [Y/n] ($# remaining)? "
+                printf "continue [Y/n] (%i remaining)? " "$#"
                 read answer
                 [ -z "$answer" ] && answer='y'
 
@@ -447,7 +445,7 @@ case $action in
         fi
         ;;
     *)
-        echo "action '$action' is unknown" >&2
+        printf "action '%s' is unknown\n" "$action" >&2
         exit 1
         ;;
 esac
